name: Run actionlint

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/*"

jobs:
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
