name: Automerge For Tasks Dragged in DONE in JIRA

# Controls when the workflow will run
on:
  repository_dispatch:
    # this is the event_type passed in from the webhook, needs to match exactly what was defined in the webhook custom data payload
    types: [event-task-done]

jobs:
  build:
    name: Auto Merge Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set env
        run: |
          PR=${{ github.event.client_payload.pull_request }}
          echo "PULL_REQ_NR=$(echo ${PR:1})" >> $GITHUB_ENV
      - name: Automatic Rebase
        uses: peter-evans/rebase@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          base: main
          head: St0rKy:${{ github.event.client_payload.branch_name }}
      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          merge-method: squash
          pull-request-number: ${{ env.PULL_REQ_NR }}



