name: Automerge For Tasks Dragged in DONE in JIRA

# Controls when the workflow will run
on:
  repository_dispatch:
    # this is the event_type passed in from the webhook, needs to match exactly what was defined in the webhook custom data payload
    types: [event-task-done]

jobs:
  build:
    name: Auto Merge Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.client_payload.pull_request }}
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          merge-method: squash
          pull-request: ${{ github.event.client_payload.pull_request }}
