name: Automerge For Tasks Dragged in DONE in JIRA

# Controls when the workflow will run
on:
  repository_dispatch:
    # this is the event_type passed in from the webhook, needs to match exactly what was defined in the webhook custom data payload
    types: [event-task-done]

jobs:
  build:
    name: Auto Merge Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set env
        run: |
          PR=${{ github.event.client_payload.pull_request }}
          echo "PULL_REQ_NR=$(echo ${PR:1})" >> $GITHUB_ENV
      - name: Automatic Rebase && Rebase Check
        id: rebase
        run: |
          git checkout ${{ github.event.client_payload.branch_name }}
          git pull
          git rebase main && (git push --force && exit 0) || (git rebase --abort && exit 1)
      - name: Rebase Fail
        if: always() && (steps.rebase.outcome == 'failure')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "REBASE FOR PULL REQUEST ${{ github.event.client_payload.pull_request_url }} FAILED (most probably because of conflicts). 
          This PR should be rebased and squash merged manually"
#      - name: Automatic Merge
#        if: always() && (steps.rebase.outcome == 'success')
#        uses: peter-evans/enable-pull-request-automerge@v2
#        with:
#          token: ${{ secrets.MY_GITHUB_TOKEN }}
#          merge-method: squash
#          pull-request-number: ${{ env.PULL_REQ_NR }}


