# This is a basic workflow to help you get started with Actions

name: Deployment Master (Multisite) Workflow

env:
  BRANCH: master

# Controls when the workflow will run
on:
  repository_dispatch:
    # this is the event_type passed in from the webhook, needs to match exactly what was defined in the webhook custom data payload
    types: [event-task-to-be-validated]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sites:
          - name: Aurelian Site
            asignee_id: 61fa6c15c224b80069c87998
            host: 34.77.168.230
            username: doctob2bfr
            password: AURELIAN_PWD
            db_name: AURELIAN_DBNAME
            db_user: AURELIAN_DBUSER
            db_pass: AURELIAN_DBPASS
            domain: AURELIAN_DOMAIN
            port: 57213
          - name: CLEMENCE Site
            asignee_id: 61fa6c15c224b80069c879981
            host: 34.77.249.81
            username: doctolibCLEMENCE
            password: CLEMENCE_PWD
            db_name: CLEMENCE_DBNAME
            db_user: CLEMENCE_DBUSER
            db_pass: CLEMENCE_DBPASS
            domain: CLEMENCE_DOMAIN
            port: 64827
          - name: Didier Site
            asignee_id: 61fa6c15c224b80069c879982
            host: 34.77.168.230
            username: doctob2bfr
            password: DIDIER_PWD
            db_name: DIDIER_DBNAME
            db_user: DIDIER_DBUSER
            db_pass: DIDIER_DBPASS
            domain: DIDIER_DOMAIN
            port: 57213
    steps:
      - uses: actions/checkout@v2
        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
        with:
          ref: ${{github.event.client_payload.branch_name}}
      - name: "Running Build for Ticket: ${{ github.event.client_payload.jira_issue }} for ${{ github.event.client_payload.assignee_name }}"
        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
        run: echo "Branch Deployed -> ${{ (github.event.client_payload.branch_name == '' && 'staging') || github.event.client_payload.branch_name }}"
#      - name: Setup Nodejs and npm
#        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
#        uses: actions/setup-node@v2
#        with:
#          node-version: "16"
#      - name: Install dependencies
#        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
#        run: cd wp-content/themes/common && yarn
#      - name: Build assets
#        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
#        run: cd wp-content/themes/common && yarn run prod
#      - name: Check assets
#        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
#        run: cd wp-content/themes/common/dist && ls -l
#      - name: Fetch Wordpress Core
#        uses: appleboy/ssh-action@v0.1.4
#        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
#        with:
#          host: ${{ matrix.sites.host }}
#          username: ${{ matrix.sites.username }}
#          password: ${{ secrets[matrix.sites.password] }}
#          port: ${{ matrix.sites.port }}
#          script: |
#            cd private/
#            rm -rf *
#            curl -O https://wordpress.org/wordpress-${{ secrets.WP_VERSION }}.zip
#            unzip wordpress-${{ secrets.WP_VERSION }}.zip
#            mv ./wordpress/* ./ && rm -rf wordpress-${{ secrets.WP_VERSION }}.zip && rm -rf ./wordpress
      - name: Write wp-config.php (Private)
        shell: bash
        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
        run: |
          chmod +x  ./.github/scripts/create_config.sh
          dbname='${{ secrets[matrix.sites.db_name] }}'
          dbuser='${{ secrets[matrix.sites.db_user] }}'
          dbpass='${{ secrets[matrix.sites.db_pass] }}'
          cachekeysalt='${{ secrets.CACHE_KEY_SALT }}'
          domain='${{ secrets[matrix.sites.domain] }}'
          prospect='${{ secrets.PROSPECT_SECRET }}'
          s3key='${{ secrets.S3UPLOADSKEY }}'
          s3secret='${{ secrets.S3UPLOADSSECRET }}'
          ./.github/scripts/create_config.sh "${dbname}" "${dbuser}" "${dbpass}" "${cachekeysalt}" "${domain}" "${prospect}" "${s3key}" "${s3secret}"
          ls -la
          cat wp-config.php
#      - name: Fetch Project from GIT (Private)
#        uses: appleboy/ssh-action@v0.1.4
#        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
#        with:
#          host: ${{ matrix.sites.host }}
#          username: ${{ matrix.sites.username }}
#          password: ${{ secrets[matrix.sites.password] }}
#          port: ${{ matrix.sites.port }}
#          script: |
#            cd private/
#            rm -rf wp-content && mkdir project && cd project
#            git clone git@github.com:doctolib/b2b-website.git .
#            git checkout ${{ env.BRANCH }}
#            git pull origin ${{ env.BRANCH }}
#            mv -v ./wp-content ../
#            cp htaccess-multisite ../.htaccess
#            cd ../ && rm -rf project
#      - name: Copy assets folder on Multisite (Private)
#        uses: garygrossgarten/github-action-scp@v0.7.3
#        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
#        with:
#          local: wp-content/themes/common/dist
#          remote: private/wp-content/themes/common/dist
#          host: ${{ matrix.sites.host }}
#          username: ${{ matrix.sites.username }}
#          password: ${{ secrets[matrix.sites.password] }}
#          port: ${{ matrix.sites.port }}
#      - name: Copy wp-config.php (Private)
#        uses: garygrossgarten/github-action-scp@v0.7.3
#        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
#        with:
#          local: "wp-config.php"
#          remote: "private/wp-config.php"
#          host: ${{ matrix.sites.host }}
#          username: ${{ matrix.sites.username }}
#          password: ${{ secrets[matrix.sites.password] }}
#          port: ${{ matrix.sites.port }}
#      - name: Move to public (Private)
#        uses: appleboy/ssh-action@v0.1.4
#        if: ${{ matrix.sites.asignee_id == github.event.client_payload.assignee_id }}
#        with:
#          host: ${{ matrix.sites.host }}
#          username: ${{ matrix.sites.username }}
#          password: ${{ secrets[matrix.sites.password] }}
#          port: ${{ matrix.sites.port }}
#          script: |
#            rm -rf public/{,.[!.],..?}*
#            cd private/
#            mv -v ./* ../public/ && mv -v ./.htaccess ../public/